// 选择柳林校区;
document.getElementById("szxq").selectedIndex = 0;
// 设置出发时间;
document.getElementById("sbDate").value = "17:03";
// 设置返校时间;
document.getElementById("edDate").value = "19:03";
// 目的地;
document.getElementById("qjmdd").value = "东门;";
// 出行方式;
document.getElementById("qjxc").value = "步行;";
// 理由;
document.getElementById("qjyy").value = "学好 Java C++, 走遍天下都不怕;\n掌握计网与算法, 面罢腾讯也称霸;";
